# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FNBR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FNBR

  target 'FNBR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FNBRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FNBR-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FNBR-tvOS

  target 'FNBR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
