# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FNBR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FNBR
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Google-Mobile-Ads-SDK', '~> 7.9'

  target 'FNBRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FNBR-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FNBR-tvOS

  target 'FNBR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
